Ext.define("MVF.controller.LabsMainController", {
    extend: "Ext.app.Controller",
    config:{
        refs:{
            LabsMain:'LabsMainView',
            GoToChemistryPage:'[itemid=labsChemistrypage]',
            GoToHematologyPage:'[itemid=labhematologypage]',
            GoToMicrobiologyPage:'[itemid=labmicrobiologypage]',
            GoToAbgPage:'[itemid=lababgpage]'
        },
        control:{
            GoToChemistryPage:{
                tap:'GoToChemistryPage'
            },
            GoToHematologyPage:{
                tap:'GoToHematologyPage'
            },
            GoToMicrobiologyPage:{
                tap:'GoToMicrobiologyPage'
            },
            GoToAbgPage:{
                tap:'GoToAbgPage'
            }
        }
    },
    GoToChemistryPage:function(){
        this.getLabsMain().push({
                 xtype:'chemistrylabs'
          });
    },
    GoToHematologyPage:function(){
        this.getLabsMain().push({
              xtype:'hematology'
        });
    },
    GoToMicrobiologyPage:function(){
        this.getLabsMain().push({
              xtype:'microbiologyview'
        });
    },
    GoToAbgPage:function(){
        this.getLabsMain().push({
              xtype:'absview'
        });
    }
});